name: flutter_offline_music
description: "A new Flutter project."
publish_to: "none"
version: 1.0.21+1

environment:
  sdk: ^3.7.0

dependencies:
  audio_metadata_reader: ^1.1.0
  audio_service: ^0.18.17
  audio_waveforms: ^2.0.2
  country_flags: ^4.1.2
  cupertino_icons: ^1.0.8
  darq: ^2.0.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_foreground_task: ^9.2.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.8.0
  google_fonts: ^8.0.2
  http: ^1.3.0
  interactive_slider: ^0.5.1
  intl: any
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.15
  just_waveform: ^0.0.6
  marquee: ^2.3.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.2
  remove_diacritic: ^0.9.0
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  timeago: ^3.7.0
  toastification: ^3.0.1
  wakelock_plus: ^1.3.0
  youtube_explode_dart: ^3.0.5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon.png
    - assets/audio-waves.png
    - assets/access_external_storage.jpg
    - assets/player_notification.png
    - assets/moon.png
    - assets/sun.png
    - assets/moon_mix_sun.jpg
    - assets/bg_music_blue.png
    - assets/bg_music_pink.png
    - assets/bg_music_1.png
    - assets/music_note_2.png
    - assets/playing.gif
    - assets/no_data.png
    - assets/disc_2.png
    - assets/music.gif
    - assets/disc_hole.png
    - assets/splash.png
    - assets/player_bg/player_bg (1).webp
    - assets/player_bg/player_bg (2).webp
    - assets/player_bg/player_bg (3).webp
    - assets/player_bg/player_bg (4).webp
    - assets/player_bg/player_bg (5).webp
    - assets/player_bg/player_bg (6).webp
    - assets/player_bg/player_bg (7).webp
    - assets/player_bg/player_bg (8).webp
    - assets/player_bg/player_bg (9).webp
    - assets/player_bg/player_bg (10).webp
    - assets/player_bg/player_bg (11).webp
    - assets/player_bg/player_bg (12).webp

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png" # Android 8+
  adaptive_icon_background: "assets/icon.png"

flutter_native_splash:
  color: "#ff405c" # Màu nền splash
  android: true
  ios: true
